set(PROJECT_MAJOR_VERSION 1)
set(PROJECT_MINOR_VERSION 0)
set(PROJECT_PATCH_VERSION 0)

set(CMAKE_PROJECT_VERSION
  ${PROJECT_MAJOR_VERSION}.${PROJECT_MINOR_VERSION}.${PROJECT_PATCH_VERSION})


function(GCCORE_BreakfastBookkeeper_ConfigureVersion target_name)
  target_compile_definitions(${target_name}
    PRIVATE
      CURRENT_PROJECT_NAME="${PROJECT_NAME}"
      CURRENT_PROJECT_VERSION="${CMAKE_PROJECT_VERSION}"
      CURRENT_PROJECT_ORGANIZATION="GCCORE"
  )
endfunction()
